Failure # 1 (occurred at 2021-06-02_20-00-41)
Traceback (most recent call last):
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 702, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 686, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/worker.py", line 1483, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.

