Failure # 1 (occurred at 2021-06-02_19-07-42)
Traceback (most recent call last):
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 702, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 686, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/worker.py", line 1481, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): [36mray::MADDPG.train_buffered()[39m (pid=11697, ip=192.168.178.102)
  File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/tune/trainable.py", line 173, in train_buffered
    result = self.train()
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 576, in train
    raise e
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 562, in train
    result = Trainable.train(self)
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/tune/trainable.py", line 232, in train
    result = self.step()
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 162, in step
    res = next(self.train_exec_impl)
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/util/iter.py", line 1075, in build_union
    item = next(it)
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/util/iter.py", line 791, in apply_foreach
    result = fn(item)
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/rllib/execution/replay_ops.py", line 48, in __call__
    self.local_actor.add_batch(batch)
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/rllib/execution/replay_buffer.py", line 383, in add_batch
    for s in batch.timeslices(self.replay_sequence_length):
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/rllib/policy/sample_batch.py", line 669, in timeslices
    finish_slice()
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/rllib/policy/sample_batch.py", line 656, in finish_slice
    {k: v.build_and_reset()
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/rllib/policy/sample_batch.py", line 656, in <dictcomp>
    {k: v.build_and_reset()
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/rllib/evaluation/sample_batch_builder.py", line 69, in build_and_reset
    batch = SampleBatch(
  File "/home/jiekaijia/anaconda3/envs/pytorch/lib/python3.8/site-packages/ray/rllib/policy/sample_batch.py", line 106, in __init__
    raise ValueError("Empty sample batch")
ValueError: Empty sample batch

